# Generated by Django 3.2.5 on 2021-07-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SortURL',
            new_name='ShortURL',
        ),
    ]
